<a href="https://colab.research.google.com/github/JamorMoussa/2IA/blob/main/utils/mlp_ga.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch pygad

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.8/80.8 kB 1.2 MB/s eta 0:00:00


In [241]:
import numpy as np
#import pygad
import torch
import torch.nn as nn

In [229]:
X = torch.rand(1000, 2)

In [230]:
y = torch.matmul(X, torch.Tensor([1, 2]).t())

In [231]:
class IsNeuronAct(nn.Module):

  def __init__(self, mask: torch.Tensor):
      super(IsNeuronAct, self).__init__()
      self.mask = nn.Parameter(torch.Tensor(mask), requires_grad=False)

  def forward(self, x: torch.Tensor) -> torch.Tensor:
    return x * self.mask

In [232]:
class MLP(nn.Module):

  def __init__(self, mask: torch.Tensor):
    super(MLP, self).__init__()

    self.l1 = nn.Linear(2, 1)
    self.act1 = IsNeuronAct(mask)
    self.l2 = nn.Linear(10, 1)

  def forward(self, x: torch.Tensor) -> torch.Tensor:
    #x = self.l1(x)
    #x = nn.ReLU()(x)
    #x = self.act1(x)
    return self.l1(x)

In [233]:
mask = torch.Tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [234]:
model = MLP(mask)

In [235]:
mse = nn.MSELoss()

In [236]:
opt = torch.optim.SGD(model.parameters(), lr=0.01)

In [237]:
num_epochs = 10
for epoch in range(num_epochs):

    outputs = model(X)

    loss = mse(outputs, y.view(-1, 1))

    opt.zero_grad()

    loss.backward()

    opt.step()

  if (epoch + 1) % 10 == 0:
    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')


Epoch [10/10], Loss: 2.9291


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/loss.py:535: UserWarning: Using a target size (torch.Size([1000])) that is different to the input size (torch.Size([1000, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [238]:
params = list(model.parameters())

In [240]:
torch.matmul(params[1].data, params[0].data)

tensor([-0.0006,  0.0007])

In [228]:
model(torch.Tensor([1, 0]))

tensor([0.2615], grad_fn=<ViewBackward0>)

In [72]:
weights = [2, 5, 10, 5, 2]
values = [20, 30, 50, 10, 15]
max_weight = 15

In [73]:
def fitness(ga_instance, solution, solution_idx):
    print(solution)
    total_value = np.sum(solution * values)
    total_weight = np.sum(solution * weights)
    if total_weight <= max_weight:
        return total_value
    else:
        return 0

In [74]:
num_genes = len(weights)
num_generations = 50
population_size = 50

initial_population = np.random.choice([0, 1], size=(population_size, num_genes))

In [75]:
ga_instance = pygad.GA(
    num_generations=num_generations,
    num_parents_mating=10,
    initial_population=initial_population.copy(),
    fitness_func=fitness,
    mutation_type="random",
    crossover_probability=0.8,
    mutation_probability=0.2,
    parent_selection_type="rank",
    crossover_type="single_point",
    keep_parents=10,
    gene_type=int,
)

In [76]:
ga_instance.run()

[1 0 1 1 0]
[0 0 0 0 1]
[0 0 0 1 0]
[0 1 1 1 1]
[1 1 0 1 1]
[0 1 1 1 0]
[1 1 0 0 0]
[0 1 1 1 1]
[0 0 0 0 1]
[0 1 1 1 0]
[0 1 0 1 1]
[1 0 0 0 0]
[0 0 0 1 0]
[1 0 0 0 1]
[1 1 1 1 0]
[0 0 0 0 1]
[1 0 1 0 0]
[1 0 0 1 0]
[0 1 0 0 0]
[1 0 0 0 1]
[1 0 1 0 0]
[0 1 1 1 0]
[1 0 1 1 1]
[1 1 0 1 1]
[0 1 0 0 1]
[1 1 0 0 0]
[1 1 1 1 1]
[0 0 0 1 1]
[1 0 0 1 1]
[1 1 1 1 0]
[1 1 0 1 1]
[0 1 0 0 1]
[1 1 1 1 0]
[1 0 0 1 0]
[0 1 0 0 1]
[0 1 1 0 0]
[0 1 1 0 1]
[1 0 1 1 0]
[0 1 0 1 1]
[1 1 0 1 1]
[0 0 1 1 1]
[0 1 0 0 0]
[1 1 0 0 0]
[0 0 0 1 0]
[0 1 0 0 1]
[1 0 0 0 0]
[0 0 0 0 1]
[1 0 0 0 1]
[1 0 0 0 0]
[1 0 1 1 1]
[1 0 0 0 0]
[0 1 1 1 1]
[0 0 0 1 1]
[1 0 1 1 1]
[0 0 1 0 0]
[0 0 0 0 0]
[0 0 1 1 0]
[1 1 1 1 0]
[1 0 1 1 1]
[0 0 1 1 0]
[0 1 1 0 1]
[0 0 0 0 0]
[0 0 1 0 1]
[0 0 1 1 0]
[0 0 1 1 0]
[1 0 1 1 1]
[1 1 1 1 0]
[0 1 1 0 1]
[1 0 1 0 0]
[1 0 1 1 1]
[0 1 1 1 1]
[1 0 1 1 1]
[0 1 1 0 1]
[1 0 1 0 1]
[0 0 1 1 0]
[0 0 1 1 0]
[1 0 1 1 0]
[1 1 1 1 1]
[0 1 1 1 1]
[0 1 1 1 1]
[0 0 1 1 0]
[1 0 1 1 0]
[0 1 0 1 1]
[1 1

In [77]:
solution, solution_fitness, solution_idx = ga_instance.best_solution()

print("Best solution:", solution)
print("Fitness value:", solution_fitness)
print("Total weight:", np.sum(solution * weights))

Best solution: [1 0 1 0 1]
Fitness value: 85
Total weight: 14
